import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          navabar aega yaha (yaha pe rakhi hui cheej sare routes pe jeagi jo is routes ke level pe hongi ya uske niche ke level pe hongi)
                
        </div>
        
        {children}
      </body>
    </html>
  );
}
